### ISSUE TITLE
割り算がおかしい

### ISSUE THREAD

**Issue by HosokawaR** [Komatsunabok/git-training-2024-09-18#6]
## 操作手順

以下参照
![image](https://github.com/user-attachments/assets/0d1a69bc-8c74-4de4-94de-9ce81ad55b25)

## 本来の想定

4 / (-2) = -2 になってほしい

## 操作環境
* OS
* OSバージョン
* ブラウザ
* ブラウザバージョン

**Comment by Komatsunabok** [comment]
#2 と同じなのでこのissueを閉じる
